import React from "react";
import { useNavigate, useParams } from "react-router-dom";
import toast from "react-hot-toast";
import { api } from "../../api";
import "./LessonPlanAgentRoute.css";

type Project = { id: string; title: string; request_text: string; page_count: number };
type Page = { id: string; title: string; document: unknown; revision: number };

export default function LessonPlanAgentRoute() {
  const { projectId } = useParams(); const nav = useNavigate(); const [projects, setProjects] = React.useState<Project[]>([]); const [project, setProject] = React.useState<Project | null>(null); const [pages, setPages] = React.useState<Page[]>([]); const [prompt, setPrompt] = React.useState(""); const [input, setInput] = React.useState(""); const [chat, setChat] = React.useState<{ role: "user" | "agent"; text: string }[]>([]); const [busy, setBusy] = React.useState(false); const [active, setActive] = React.useState(0);
  const load = React.useCallback(async () => { const list = (await api.get<{ items: Project[] }>("/lesson-plans/projects")).data.items; setProjects(list); if (projectId) { setProject((await api.get<Project>(`/lesson-plans/projects/${projectId}`)).data); setPages((await api.get<{ items: Page[] }>(`/lesson-plans/projects/${projectId}/pages`)).data.items); } else setProject(null); }, [projectId]); React.useEffect(() => { void load(); }, [load]);
  const create = async () => { setBusy(true); try { const p = (await api.post<Project>("/lesson-plans/projects", { title: prompt.slice(0, 28), request_text: prompt })).data; nav(`/teacher/lesson-plan-agent/${p.id}`); } finally { setBusy(false); } };
  const send = async () => { if (!project || !input.trim()) return; const text = input.trim(); setInput(""); setChat(x => [...x, { role: "user", text }]); try { const r = (await api.post(`/lesson-plans/projects/${project.id}/requirements/chat`, { content: text })).data; setChat(x => [...x, { role: "agent", text: r.message }]); } catch { toast.error("消息发送失败，请稍后重试"); } };
  const generate = async () => { if (!project) return; setBusy(true); try { await api.post(`/lesson-plans/projects/${project.id}/generate`); await load(); toast.success("已生成，请继续调整"); } finally { setBusy(false); } };
  if (!project) return <div className="lesson-home"><header className="lesson-topbar"><div className="lesson-brand"><b>HKU</b><span>LESSON PLAN AGENT</span></div><div className="lesson-context"><span>学案工作台</span><i /> <span>模型由管理员统一配置</span></div></header><main className="lesson-home-grid"><section className="lesson-create-card"><div className="lesson-create-copy"><div className="lesson-spark">✦</div><span className="lesson-eyebrow">YOUR NEXT TEACHING MATERIAL</span><h1>把教学想法，<em>变成一份好学案。</em></h1><p>描述课程主题、学生水平和你想要的练习类型，Agent 会先理解需求，再帮你搭建一份清晰、可打印的教学材料。</p></div><div className="lesson-composer"><textarea value={prompt} onChange={e => setPrompt(e.target.value)} placeholder="例如：高一物理牛顿第二定律学案，包含分层练习和答案" rows={4} /><div className="lesson-composer-footer"><span>{prompt.length ? `${prompt.length} 字` : "支持自然语言描述"}</span><button className="lesson-button primary" onClick={() => void create()} disabled={busy || !prompt.trim()}>{busy ? "创建中…" : "开始创建"}<b>↗</b></button></div></div></section><section className="lesson-projects"><div className="lesson-section-head"><div><span className="lesson-eyebrow">RECENT PROJECTS</span><h2>最近项目</h2></div><span>{projects.length} 个项目</span></div>{projects.length ? <div className="lesson-project-list">{projects.map(p => <button className="lesson-project-card" key={p.id} onClick={() => nav(`/teacher/lesson-plan-agent/${p.id}`)}><div className="lesson-project-meta"><span>学案</span><i /> <span>{p.page_count || 0} 页</span><b>↗</b></div><h3>{p.title}</h3><p>{p.request_text}</p></button>)}</div> : <div className="lesson-empty-projects"><span>✦</span><strong>你的项目会出现在这里</strong><p>从左侧描述第一个教学想法开始。</p></div>}</section><aside className="lesson-settings-card"><div className="lesson-settings-icon">⌁</div><span className="lesson-eyebrow">WORKSPACE SETTINGS</span><h2>业务配置</h2><p>AI Provider 与模型由管理员统一配置。</p><div className="lesson-status"><i /> 平台统一管理</div></aside></main></div>;
  return <div className="lesson-workspace"><header className="lesson-workspace-head"><button className="lesson-back" onClick={() => nav("/teacher/lesson-plan-agent")}>←</button><div className="lesson-workspace-title"><span className="lesson-eyebrow">LESSON PLAN AGENT</span><h1>{project.title}</h1></div><div className="lesson-workspace-status"><i /> 自动保存</div><button className="lesson-button primary" onClick={() => void generate()} disabled={busy}>{busy ? "生成中…" : "生成学案 PDF"}<b>↗</b></button></header><div className="lesson-workspace-grid"><aside className="lesson-pages"><div className="lesson-panel-head"><div><span className="lesson-eyebrow">OUTLINE</span><h2>页面大纲</h2></div><strong>{pages.length}</strong></div>{pages.length ? pages.map((p, i) => <button className={`lesson-page-item ${i === active ? "active" : ""}`} key={p.id} onClick={() => setActive(i)}><span>{String(i + 1).padStart(2, "0")}</span><div><b>{p.title || "未命名页面"}</b><small>{i === active ? "正在查看" : "点击查看页面"}</small></div></button>) : <div className="lesson-pages-empty">生成后会显示页面大纲</div>}</aside><main className="lesson-chat-panel"><div className="lesson-chat-head"><div><span className="lesson-eyebrow">CONVERSATION</span><h2>和 Agent 一起完善需求</h2></div><span className="lesson-online"><i />在线</span></div><div className="lesson-chat-stream">{chat.length ? chat.map((m, i) => <div className={`lesson-message ${m.role}`} key={`${i}-${m.text}`}><span>{m.role === "user" ? "你" : "Agent"}</span><p>{m.text}</p></div>) : <div className="lesson-chat-welcome"><div className="lesson-spark">✦</div><h3>从你的教学目标开始</h3><p>告诉我学生是谁、要学会什么，以及你希望学案包含哪些内容。</p></div>}</div><div className="lesson-chat-composer"><textarea value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); void send(); } }} placeholder="回复 Agent，继续补充你的要求…" rows={2} /><div><span>Enter 发送 · Shift + Enter 换行</span><button className="lesson-send" onClick={() => void send()} disabled={!input.trim()}>↑</button></div></div></main><aside className="lesson-adjust-panel"><div className="lesson-panel-head"><div><span className="lesson-eyebrow">TEACHER CONTROL</span><h2>教师调整</h2></div><span className="lesson-adjust-dot">●</span></div><div className="lesson-adjust-content"><div className="lesson-adjust-illustration">✦</div><h3>让每一页更贴合你的课堂</h3><p>生成学案后，你可以继续调整页面文字、结构与视觉内容，再导出最终 PDF。</p><div className="lesson-adjust-list"><span>✓ 编辑页面内容</span><span>✓ 调整练习难度</span><span>✓ 导出可打印 PDF</span></div></div></aside></div></div>;
}
