import React from "react";
import { useNavigate } from "react-router-dom";
import { api, fileApi, teacherVideoApi, type Course, type VideoProject } from "../../../api";
import styles from "../styles/AiVideoRoute.module.css";

export default function AiVideoRoute() {
  const [projects, setProjects] = React.useState<VideoProject[]>([]); const [courses, setCourses] = React.useState<Course[]>([]); const [title, setTitle] = React.useState(""); const [text, setText] = React.useState(""); const [courseId, setCourseId] = React.useState(""); const [objectives, setObjectives] = React.useState(""); const [audience, setAudience] = React.useState(""); const [duration, setDuration] = React.useState(120); const [language, setLanguage] = React.useState("zh-HK"); const [style, setStyle] = React.useState("lecture"); const [provider, setProvider] = React.useState<"coze" | "local">("local"); const [voice, setVoice] = React.useState(true); const [captions, setCaptions] = React.useState(true); const [avatar, setAvatar] = React.useState(false); const [file, setFile] = React.useState<File | null>(null); const [busy, setBusy] = React.useState(false); const nav = useNavigate();
  const load = React.useCallback(() => Promise.all([teacherVideoApi.listProjects(), api.get<Course[]>("/courses")]).then(([p, c]) => { setProjects(p.data); setCourses(c.data); }).catch(() => undefined), []); React.useEffect(() => { void load(); }, [load]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); if (!title.trim()) return; setBusy(true); try { const p = (await teacherVideoApi.createProject({ title, course_id: courseId || undefined, input_text: text, provider, learning_objectives: objectives.split("\n").map((x) => x.trim()).filter(Boolean), audience, duration_seconds: duration, language, style, voice_enabled: voice, captions_enabled: captions, avatar_enabled: avatar })).data; if (file) { const uploaded = await fileApi.upload(file); await teacherVideoApi.addSource(p.id, { file_asset_id: uploaded.data.id, source_type: "upload", title: file.name }); } nav(`/teacher/ai-video/${p.id}`); } finally { setBusy(false); } };
  return <main className={styles.page}><header className={styles.heading}><div><span>AI TEACHING VIDEO</span><h1>AI 教学视频</h1><p>把课程资料整理成短讲解视频，先从脚本、旁白、字幕和卡片视频开始。</p></div><form className={styles.create} onSubmit={create}><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="视频标题" /><select value={courseId} onChange={(e) => setCourseId(e.target.value)}><option value="">选择课程（可选）</option>{courses.map((course) => <option value={course.id} key={course.id}>{course.code} · {course.name}</option>)}</select><textarea value={text} onChange={(e) => setText(e.target.value)} placeholder="粘贴讲稿或教学重点（可选）" rows={3} /><textarea value={objectives} onChange={(e) => setObjectives(e.target.value)} placeholder="教学目标，每行一个" rows={2} /><input value={audience} onChange={(e) => setAudience(e.target.value)} placeholder="学习对象，例如本科生" /><div className={styles.row}><label>时长 <input type="number" min={15} max={900} value={duration} onChange={(e) => setDuration(Number(e.target.value))} /></label><label>语言 <select value={language} onChange={(e) => setLanguage(e.target.value)}><option value="zh-HK">繁体中文</option><option value="zh-CN">简体中文</option><option value="en">English</option></select></label></div><div className={styles.row}><label>风格 <select value={style} onChange={(e) => setStyle(e.target.value)}><option value="lecture">课堂讲解</option><option value="storytelling">故事化</option><option value="summary">重点速览</option></select></label><label>资料 <input type="file" accept=".pdf,.ppt,.pptx,.doc,.docx,.png,.jpg,.jpeg" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label></div><select value={provider} onChange={(e) => setProvider(e.target.value as "coze" | "local")}><option value="local">Local provider</option><option value="coze">Coze API</option></select><div className={styles.checks}><label><input type="checkbox" checked={voice} onChange={(e) => setVoice(e.target.checked)} />旁白</label><label><input type="checkbox" checked={captions} onChange={(e) => setCaptions(e.target.checked)} />字幕</label><label><input type="checkbox" checked={avatar} onChange={(e) => setAvatar(e.target.checked)} />数字人</label></div><button disabled={busy || !title.trim()}>{busy ? "创建中…" : "新建项目"}</button></form></header><section className={styles.list}><h2>我的视频项目</h2>{projects.length ? projects.map((p) => <button className={styles.card} key={p.id} onClick={() => nav(`/teacher/ai-video/${p.id}`)}><strong>{p.title}</strong><span>{p.provider} · {p.status} · {p.duration_seconds} 秒</span><small>{new Date(p.updated_at).toLocaleString("zh-CN")}</small></button>) : <div className={styles.empty}>还没有视频项目，先创建一个短教学视频。</div>}</section></main>;
}
