import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const API = 'http://localhost:8000';
type Doc = {id:number; filename:string; file_type:string; status:string; pages?:number};
type Evidence = {filename:string; page:number; slide_number?:number; chunk_id:number; content:string; confidence:number; has_image:boolean};

function renderMarkdown(value:string) {
  return value.split(/```/).map((part, i) => i % 2 ? <pre key={i}><code>{part.replace(/^\w+\n/, '')}</code></pre> : <p key={i}>{part.split(/\n\n+/).map((x,j)=><span key={j}>{x}<br/></span>)}</p>);
}

function App(){
  const [files,setFiles] = useState<File[]>([]), [docs,setDocs] = useState<Doc[]>([]), [jobs,setJobs] = useState<any[]>([]);
  const [selected,setSelected] = useState<number[]>([]), [conversation,setConversation] = useState<any>(null), [messages,setMessages] = useState<any[]>([]), [question,setQuestion] = useState('');
  const [evidence,setEvidence] = useState<Evidence[]>([]), [provider,setProvider] = useState(''), [model,setModel] = useState(''), [apiKey,setApiKey] = useState(''), [temperature,setTemperature] = useState(.2), [images,setImages] = useState(true), [summary,setSummary] = useState(false), [busy,setBusy] = useState(false);
  const readyDocs = useMemo(()=>docs.filter(d=>['ready','partial_ready'].includes(d.status)),[docs]);
  useEffect(()=>{ const load=async()=>setDocs(await fetch(API+'/api/v1/documents').then(r=>r.json()).catch(()=>[])); load(); const t=setInterval(load,2000); return()=>clearInterval(t)},[]);
  const upload=async()=>{const fd=new FormData(); files.forEach(f=>fd.append('files',f)); const r=await fetch(API+'/api/v1/documents',{method:'POST',body:fd}); setJobs(await r.json()); setFiles([])};
  const newConversation=async()=>{const c=await fetch(API+'/api/v1/chat/conversations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document_ids:selected})}).then(r=>r.json()); setConversation(c); setMessages([]); setEvidence([])};
  const send=async()=>{if(!conversation || !question.trim() || busy)return; const text=question; setQuestion(''); setMessages(m=>[...m,{role:'user',content:text}]); setBusy(true); const body={content:text,document_ids:selected,provider:provider||undefined,model:model||undefined,api_key:apiKey||undefined,temperature,include_images:images,full_summary:summary};
    try { const r=await fetch(`${API}/api/v1/chat/conversations/${conversation.id}/stream`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const reader=r.body?.getReader(); const decoder=new TextDecoder(); let answer=''; if(reader){let buffer=''; while(true){const {done,value}=await reader.read(); if(done)break; buffer+=decoder.decode(value,{stream:true}); const events=buffer.split('\n\n'); buffer=events.pop()||''; for(const event of events){const line=event.split('\n').find(x=>x.startsWith('data: ')); if(!line)continue; const data=JSON.parse(line.slice(6)); if(data.type==='token'){answer+=data.content; setMessages(m=>[...m.filter(x=>x._stream!==true),{role:'assistant',content:answer,_stream:true}])} if(data.evidence)setEvidence(data.evidence); if(data.type==='fallback'){answer=data.content; setEvidence(data.evidence||[]); setMessages(m=>[...m,{role:'assistant',content:answer}])}}}}}
    catch(e){setMessages(m=>[...m,{role:'assistant',content:'请求失败：请检查后端、服务端配置或 API Key。'}])} finally{setBusy(false)}
  };
  return <main><header><div><h1>Evidence Desk</h1><p>结构化 PDF / PPTX 解析与证据对话</p></div><button onClick={newConversation}>新建对话</button></header>
    <section className="grid"><aside><h2>文档</h2><input type="file" accept=".pdf,.pptx" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/><button disabled={!files.length} onClick={upload}>上传并处理</button>{jobs.map(j=><div className="muted" key={j.job_id}>任务 #{j.job_id} {j.filename}</div>)}<div className="docs">{readyDocs.map(d=><label key={d.id}><input type="checkbox" checked={selected.includes(d.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,d.id]:s.filter(x=>x!==d.id))}/>{d.filename}<small>{d.status} · {d.pages||0} 页</small></label>)}</div><h2>对话配置</h2><input placeholder="provider（留空使用服务端）" value={provider} onChange={e=>setProvider(e.target.value)}/><input placeholder="model" value={model} onChange={e=>setModel(e.target.value)}/><input type="password" placeholder="API Key（仅当前请求）" value={apiKey} onChange={e=>setApiKey(e.target.value)}/><label>temperature <input type="number" min="0" max="2" step=".1" value={temperature} onChange={e=>setTemperature(Number(e.target.value))}/></label><label><input type="checkbox" checked={images} onChange={e=>setImages(e.target.checked)}/>附加页面图片</label><label><input type="checkbox" checked={summary} onChange={e=>setSummary(e.target.checked)}/>完整总结模式</label></aside>
    <section className="chat"><div className="messages">{!conversation&&<div className="empty">选择 ready 文档后点击“新建对话”</div>}{messages.map((m,i)=><article className={m.role} key={i}><b>{m.role==='user'?'你':'AI'}</b>{renderMarkdown(m.content)}</article>)}</div><div className="composer"><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="询问已选 PDF / PPTX…"/><button disabled={busy||!conversation} onClick={send}>{busy?'生成中…':'发送'}</button></div></section>
    <aside className="evidence"><h2>检索证据</h2>{evidence.map(e=><div className="evidence-card" key={e.chunk_id}><strong>{e.filename} {e.slide_number?`slide ${e.slide_number}`:`p.${e.page}`}</strong><span>confidence {Number(e.confidence).toFixed(2)} {e.has_image?' · image':''}</span><p>{e.content.slice(0,260)}</p><a href={`${API}/api/v1/documents/${readyDocs.find(d=>d.filename===e.filename)?.id||''}/artifacts/${e.slide_number?`slides/slide-${String(e.slide_number).padStart(3,'0')}.json`:`pages/page-${String(e.page).padStart(3,'0')}.json`}`} target="_blank">打开 JSON</a></div>)}</aside></section></main>
}
createRoot(document.getElementById('root')!).render(<App/>);
