import React, { useEffect } from "react";
import toast from "react-hot-toast";
import { AgentConversation, AgentMessage, api } from "../../api";

export default function CoursewareAgent() {
  const [conversations, setConversations] = React.useState<AgentConversation[]>([]); const [activeId, setActiveId] = React.useState<string | null>(null); const [messages, setMessages] = React.useState<AgentMessage[]>([]); const [draft, setDraft] = React.useState(""); const [streaming, setStreaming] = React.useState(false); const [deleteId, setDeleteId] = React.useState<string | null>(null);
  const loadConversations = React.useCallback(() => api.get<AgentConversation[]>("/agent/conversations").then((r) => { setConversations(r.data); if (!activeId && r.data[0]) setActiveId(r.data[0].id); }).catch(() => undefined), [activeId]);
  useEffect(() => { loadConversations(); }, [loadConversations]);
  useEffect(() => { if (activeId) api.get<AgentConversation>(`/agent/conversations/${activeId}`).then((r) => setMessages(r.data.messages || [])).catch(() => setMessages([])); }, [activeId]);
  const createConversation = async () => { const { data } = await api.post<AgentConversation>("/agent/conversations", { title: "新对话" }); setConversations((c) => [data, ...c]); setActiveId(data.id); setMessages([]); };
  const send = async (event: React.FormEvent) => { event.preventDefault(); const text = draft.trim(); if (!text || streaming) return; let id = activeId; setStreaming(true); try { if (!id) { const { data } = await api.post<AgentConversation>("/agent/conversations", { title: text.slice(0, 24) }); setConversations((c) => [data, ...c]); id = data.id; setActiveId(id); } setDraft(""); const userMessage = await api.post<AgentMessage>(`/agent/conversations/${id}/messages`, { role: "user", content: text }); setMessages((m) => [...m, userMessage.data]); const reply = `收到你的问题：“${text}”。这是PPT Agent 的演示回复：我可以帮助你梳理课程重点、设计课堂活动，并根据教学目标组织课件结构。真实课件生成能力将在后续版本接入。`; const tempId = `stream-${Date.now()}`; setMessages((m) => [...m, { id: tempId, conversation_id: id!, role: "assistant", content: "", citations: [], model: "demo", created_at: new Date().toISOString() }]); for (let i = 1; i <= reply.length; i += 1) { await new Promise((resolve) => window.setTimeout(resolve, 18)); setMessages((m) => m.map((item) => item.id === tempId ? { ...item, content: reply.slice(0, i) } : item)); } const saved = await api.post<AgentMessage>(`/agent/conversations/${id}/messages`, { role: "assistant", content: reply, model: "demo" }); setMessages((m) => m.map((item) => item.id === tempId ? saved.data : item)); } catch { toast.error("消息发送失败，请稍后重试"); } finally { setStreaming(false); } };
  const remove = async () => { if (!deleteId) return; await api.delete(`/agent/conversations/${deleteId}`); const next = conversations.filter((c) => c.id !== deleteId); setConversations(next); setDeleteId(null); setActiveId(next[0]?.id || null); setMessages([]); };
  return <div className="agent-page"><div className="agent-history"><div className="agent-history-head"><div><p className="eyebrow">PPT AGENT</p><h2>PPT Agent</h2></div><button className="icon-button" onClick={createConversation} aria-label="新建会话"><i className="fas fa-plus" /></button></div><button className="new-conversation" onClick={createConversation}><i className="fas fa-pen-to-square" /> 新建对话</button><div className="conversation-list">{conversations.map((c) => <div className={`conversation-row ${c.id === activeId ? "active" : ""}`} key={c.id}><button onClick={() => setActiveId(c.id)}><strong>{c.title}</strong><small>{new Date(c.created_at).toLocaleDateString("zh-CN")}</small></button><button className="delete-conversation" onClick={() => setDeleteId(c.id)} aria-label="删除会话"><i className="fas fa-trash" /></button></div>)}{!conversations.length && <span className="history-empty">还没有对话记录</span>}</div></div><section className="agent-chat"><header className="agent-chat-head"><div><p className="eyebrow">INTELLIGENT TEACHING</p><h1>和 PPT Agent 聊聊</h1></div><span className="agent-status"><i className="fas fa-circle" /> Demo 模式</span></header><div className="agent-messages">{!messages.length ? <div className="agent-empty"><i className="fas fa-robot" /><h2>从一个教学想法开始</h2><p>试试询问课程结构、课堂活动或课件大纲。</p><div className="suggestions">{["帮我设计一节 50 分钟的课堂", "总结这门课的核心知识点", "给出一个小组讨论活动"].map((s) => <button key={s} onClick={() => setDraft(s)}>{s}</button>)}</div></div> : messages.map((m) => <div className={`agent-message ${m.role}`} key={m.id}><span className="message-avatar"><i className={`fas ${m.role === "assistant" ? "fa-robot" : "fa-user"}`} /></span><div><small>{m.role === "assistant" ? "PPT Agent" : "你"}</small><p>{m.content}{streaming && m.id.startsWith("stream-") && <span className="cursor" />}</p></div></div>)}</div><form className="agent-composer" onSubmit={send}><textarea value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="输入你的教学问题…" rows={1} disabled={streaming} /><button type="submit" disabled={!draft.trim() || streaming}><i className="fas fa-arrow-up" /></button></form></section>{deleteId && <div className="modal-backdrop"><div className="confirm-modal"><h3>删除这段对话？</h3><p>删除后将无法恢复对话记录。</p><div><button onClick={() => setDeleteId(null)}>取消</button><button className="danger" onClick={remove}>确认删除</button></div></div></div>}</div>;
}

