import React from "react";
import { useSearchParams } from "react-router-dom";
import { studentApi, type CoursewareQuery, type AgentMessage } from "../../api";
import styles from "./CoursewareAgentRoute.module.css";
type Message={role:"user"|"assistant";text:string;result?:CoursewareQuery};
type Conversation={id:string;title:string;created_at:string};
export default function CoursewareAgentRoute(){
 const [params]=useSearchParams(); const [conversations,setConversations]=React.useState<Conversation[]>([]); const [active,setActive]=React.useState<Conversation|null>(null); const [question,setQuestion]=React.useState(""); const [messages,setMessages]=React.useState<Message[]>([]); const [typing,setTyping]=React.useState(""); const [busy,setBusy]=React.useState(false); const bottom=React.useRef<HTMLDivElement>(null);
 const load=async()=>{const list=(await studentApi.coursewareConversations()).data as Conversation[];setConversations(list); const fresh=(await studentApi.createCoursewareConversation()).data as Conversation; setConversations(x=>[fresh,...x]);setActive(fresh);setMessages([]);}; React.useEffect(()=>{void load();},[]); React.useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"});},[messages,typing]);
 const open=async(c:Conversation)=>{setActive(c);const data=(await studentApi.coursewareConversation(c.id)).data;setMessages((data.messages||[]).map((m:AgentMessage)=>({role:m.role,text:m.content,result:m.citations as CoursewareQuery|undefined})));};
 const newChat=async()=>{const c=(await studentApi.createCoursewareConversation()).data as Conversation;setConversations(x=>[c,...x]);setActive(c);setMessages([]);setQuestion("");};
 const remove=async(id:string)=>{await studentApi.deleteCoursewareConversation(id);setConversations(x=>x.filter(c=>c.id!==id));if(active?.id===id)await newChat();};
 const submit=async(e?:React.FormEvent,preset?:string)=>{e?.preventDefault();const prompt=(preset??question).trim();if(!prompt||busy||!active)return;setQuestion("");setMessages(x=>[...x,{role:"user",text:prompt}]);setBusy(true);await studentApi.appendCoursewareMessage(active.id,{role:"user",content:prompt});try{const result=(await studentApi.coursewareQuery({question:prompt,course_id:params.get("courseId")||undefined})).data;setMessages(x=>[...x,{role:"assistant",text:result.answer,result}]);await studentApi.appendCoursewareMessage(active.id,{role:"assistant",content:result.answer,citations:result.citations,model:result.model});let i=0;const timer=window.setInterval(()=>{i+=Math.max(1,Math.ceil(result.answer.length/90));setTyping(result.answer.slice(0,i));if(i>=result.answer.length){clearInterval(timer);setTyping("");}},24);}catch{setMessages(x=>[...x,{role:"assistant",text:"暂时无法连接课程知识库，请稍后再试。"}]);}finally{setBusy(false);}};
 return <main className={styles.shell}><aside className={styles.history}><div className={styles.historyBrand}><div className={styles.brandMark}>HKU</div><div><span className={styles.kicker}>COURSEWARE RAG</span><b>AI 讲师</b></div></div><button className={styles.newChat} onClick={()=>void newChat()}>＋ 新对话</button><div className={styles.historyTitle}>历史对话</div><nav className={styles.conversations}>{conversations.map(c=><div className={`${styles.conversation} ${active?.id===c.id?styles.selected:""}`} key={c.id}><button onClick={()=>void open(c)}><span>{c.title||"新对话"}</span><small>{new Date(c.created_at).toLocaleDateString("zh-CN")}</small></button><button className={styles.delete} onClick={()=>void remove(c.id)} aria-label="删除对话">×</button></div>)}</nav></aside><section className={styles.chat}><header className={styles.header}><div><span className={styles.kicker}>YOUR COURSE COMPANION</span><h1>{active?.title||"新对话"}</h1><p>基于你的课程材料，给出有依据的讲解。</p></div><div className={styles.status}><i/>知识库在线</div></header><div className={styles.messages}>{!messages.length&&<div className={styles.welcome}><div className={styles.orb}>✦</div><h2>今天想了解哪一部分？</h2><p>提出关于课程概念、课件内容或作业要求的问题。</p><div className={styles.prompts}>{["帮我梳理本周课件的重点","用一个例子解释核心概念","这份作业应该从哪里开始？"].map(x=><button key={x} onClick={()=>{setQuestion(x);void submit(undefined,x)}}>{x}<span>↗</span></button>)}</div></div>}{messages.map((m,i)=><article className={`${styles.message} ${m.role==="user"?styles.user:styles.assistant}`} key={i}><div className={styles.avatar}>{m.role==="user"?"你":"✦"}</div><div className={styles.bubble}><span className={styles.meta}>{m.role==="user"?"STUDENT":"AI LECTURER"}</span><p>{m.role==="assistant"&&i===messages.length-1&&typing?typing:m.text}{m.role==="assistant"&&i===messages.length-1&&typing&&<b className={styles.cursor}/>}</p>{m.result?.citations?.length?<div className={styles.references}><span>课程参考</span>{m.result.citations.map((c,j)=><a href={c.href} key={j}>↗ {c.chapter_title} · {c.material_title}</a>)}</div>:null}</div></article>)}{busy&&<div className={`${styles.message} ${styles.assistant}`}><div className={styles.avatar}>✦</div><div className={styles.bubble}><span className={styles.meta}>AI LECTURER</span><div className={styles.dots}><i/><i/><i/></div></div></div>}<div ref={bottom}/></div><form className={styles.composer} onSubmit={submit}><div className={styles.inputWrap}><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="问问你的课程讲师…" rows={1}/><span>Enter 发送 · Shift + Enter 换行</span></div><button disabled={busy||!question.trim()}>↑</button></form></section></main>;
}
