import React from "react";
import { useSearchParams } from "react-router-dom";
import { studentApi, type CoursewareQuery } from "../../api";
import styles from "./CoursewareAgentRoute.module.css";
type Message = { role: "user" | "assistant"; text: string; result?: CoursewareQuery };
export default function CoursewareAgentRoute() {
 const [params]=useSearchParams(); const [question,setQuestion]=React.useState(""); const [messages,setMessages]=React.useState<Message[]>([]); const [typing,setTyping]=React.useState(""); const [busy,setBusy]=React.useState(false); const bottomRef=React.useRef<HTMLDivElement>(null);
 React.useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:"smooth"});},[messages,typing]);
 const submit=async(event?:React.FormEvent, preset?: string)=>{event?.preventDefault();const prompt=(preset ?? question).trim();if(!prompt||busy)return;setQuestion("");setMessages(x=>[...x,{role:"user",text:prompt}]);setBusy(true);setTyping("");try{const result=(await studentApi.coursewareQuery({question:prompt,course_id:params.get("courseId")||undefined})).data;setMessages(x=>[...x,{role:"assistant",text:result.answer,result}]);let index=0;const timer=window.setInterval(()=>{index+=Math.max(1,Math.ceil(result.answer.length/90));setTyping(result.answer.slice(0,index));if(index>=result.answer.length){window.clearInterval(timer);setTyping("");}},24);}catch{setMessages(x=>[...x,{role:"assistant",text:"暂时无法连接课程知识库，请稍后再试。"}]);}finally{setBusy(false);}};
 return <main className={styles.shell}><header className={styles.header}><div className={styles.brandMark}>HKU</div><div><span className={styles.kicker}>COURSEWARE RAG</span><h1>AI 讲师</h1><p>从课程材料中，获得有依据的解释。</p></div><div className={styles.status}><i/>知识库在线</div></header><section className={styles.stage}><div className={styles.messages}>{!messages.length&&<div className={styles.welcome}><div className={styles.orb}><span>✦</span></div><span className={styles.kicker}>YOUR COURSE COMPANION</span><h2>今天想了解哪一部分？</h2><p>提出关于课程概念、课件内容或作业要求的问题，我会优先从你的课程材料中寻找答案。</p><div className={styles.prompts}>{["帮我梳理本周课件的重点","用一个例子解释核心概念","这份作业应该从哪里开始？"].map(item=><button key={item} onClick={()=>{setQuestion(item);void submit(undefined,item);}}>{item}<span>↗</span></button>)}</div></div>}{messages.map((message,index)=><article className={`${styles.message} ${message.role==="user"?styles.user:styles.assistant}`} key={`${message.role}-${index}`}><div className={styles.avatar}>{message.role==="user"?"你":"✦"}</div><div className={styles.bubble}><span className={styles.meta}>{message.role==="user"?"STUDENT":"AI LECTURER"}</span><p>{message.role==="assistant"&&index===messages.length-1&&typing?typing:message.text}{message.role==="assistant"&&index===messages.length-1&&typing&&<b className={styles.cursor}/>}</p>{message.result?.citations?.length?<div className={styles.references}><span>课程参考</span>{message.result.citations.map((c,i)=><a href={c.href} key={`${c.material_id}-${i}`}>↗ {c.chapter_title} · {c.material_title}{c.page_number?` · 第 ${c.page_number} 页`:""}</a>)}</div>:null}</div></article>)}{busy&&<div className={`${styles.message} ${styles.assistant}`}><div className={styles.avatar}>✦</div><div className={styles.bubble}><span className={styles.meta}>AI LECTURER</span><div className={styles.dots}><i/><i/><i/></div></div></div>}<div ref={bottomRef}/></div><form className={styles.composer} onSubmit={submit}><div className={styles.inputWrap}><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void submit();}}} placeholder="问问你的课程讲师…" rows={1}/><span>Enter 发送 · Shift + Enter 换行</span></div><button disabled={busy||!question.trim()} aria-label="发送">↑</button></form></section></main>;
}

