"""AI teaching video projects and provider-neutral jobs."""
from alembic import op
import sqlalchemy as sa

revision = "0018_ai_video"
down_revision = "0017_ppt_editor_assets"
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("video_projects", sa.Column("id", sa.String(36), primary_key=True), sa.Column("owner_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("course_id", sa.String(36), sa.ForeignKey("courses.id", ondelete="SET NULL")), sa.Column("title", sa.String(200), nullable=False, server_default="未命名教学视频"), sa.Column("description", sa.Text(), nullable=False, server_default=""), sa.Column("provider", sa.String(20), nullable=False, server_default="coze"), sa.Column("status", sa.String(30), nullable=False, server_default="draft"), sa.Column("language", sa.String(30), nullable=False, server_default="zh-HK"), sa.Column("duration_seconds", sa.Integer(), nullable=False, server_default="120"), sa.Column("style", sa.String(60), nullable=False, server_default="lecture"), sa.Column("input_text", sa.Text(), nullable=False, server_default=""), sa.Column("config_json", sa.JSON(), nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_video_projects_owner_id", "video_projects", ["owner_id"]); op.create_index("ix_video_projects_course_id", "video_projects", ["course_id"]); op.create_index("ix_video_projects_status", "video_projects", ["status"])
    op.create_table("video_sources", sa.Column("id", sa.String(36), primary_key=True), sa.Column("project_id", sa.String(36), sa.ForeignKey("video_projects.id", ondelete="CASCADE"), nullable=False), sa.Column("file_asset_id", sa.String(36), sa.ForeignKey("file_assets.id", ondelete="SET NULL")), sa.Column("source_type", sa.String(30), nullable=False, server_default="text"), sa.Column("title", sa.String(255), nullable=False, server_default="讲稿"), sa.Column("extracted_text", sa.Text(), nullable=False, server_default=""), sa.Column("metadata_json", sa.JSON(), nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_video_sources_project_id", "video_sources", ["project_id"]); op.create_index("ix_video_sources_file_asset_id", "video_sources", ["file_asset_id"])
    op.create_table("video_scenes", sa.Column("id", sa.String(36), primary_key=True), sa.Column("project_id", sa.String(36), sa.ForeignKey("video_projects.id", ondelete="CASCADE"), nullable=False), sa.Column("order_index", sa.Integer(), nullable=False, server_default="0"), sa.Column("title", sa.String(200), nullable=False, server_default="场景"), sa.Column("narration", sa.Text(), nullable=False, server_default=""), sa.Column("onscreen_text", sa.Text(), nullable=False, server_default=""), sa.Column("visual_prompt", sa.Text(), nullable=False, server_default=""), sa.Column("duration_seconds", sa.Integer(), nullable=False, server_default="15"), sa.Column("status", sa.String(30), nullable=False, server_default="draft"), sa.Column("metadata_json", sa.JSON(), nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_video_scenes_project_id", "video_scenes", ["project_id"]); op.create_unique_constraint("uq_video_scene_order", "video_scenes", ["project_id", "order_index"])
    op.create_table("video_generation_jobs", sa.Column("id", sa.String(36), primary_key=True), sa.Column("project_id", sa.String(36), sa.ForeignKey("video_projects.id", ondelete="CASCADE"), nullable=False), sa.Column("owner_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("provider", sa.String(20), nullable=False, server_default="coze"), sa.Column("provider_job_id", sa.String(255)), sa.Column("status", sa.String(30), nullable=False, server_default="queued"), sa.Column("stage", sa.String(80), nullable=False, server_default="queued"), sa.Column("progress", sa.Integer(), nullable=False, server_default="0"), sa.Column("current_scene", sa.Integer(), nullable=False, server_default="0"), sa.Column("total_scenes", sa.Integer(), nullable=False, server_default="0"), sa.Column("result_json", sa.JSON(), nullable=False, server_default="{}"), sa.Column("error_message", sa.Text()), sa.Column("idempotency_key", sa.String(255), nullable=False), sa.Column("queue_task_id", sa.String(255)), sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_video_generation_jobs_project_id", "video_generation_jobs", ["project_id"]); op.create_index("ix_video_generation_jobs_owner_id", "video_generation_jobs", ["owner_id"]); op.create_index("ix_video_generation_jobs_provider_job_id", "video_generation_jobs", ["provider_job_id"]); op.create_index("ix_video_generation_jobs_status", "video_generation_jobs", ["status"]); op.create_index("ix_video_generation_jobs_queue_task_id", "video_generation_jobs", ["queue_task_id"]); op.create_unique_constraint("uq_video_job_owner_idempotency", "video_generation_jobs", ["owner_id", "idempotency_key"])
    op.create_table("video_assets", sa.Column("id", sa.String(36), primary_key=True), sa.Column("project_id", sa.String(36), sa.ForeignKey("video_projects.id", ondelete="CASCADE"), nullable=False), sa.Column("job_id", sa.String(36), sa.ForeignKey("video_generation_jobs.id", ondelete="CASCADE"), nullable=False), sa.Column("asset_type", sa.String(30), nullable=False, server_default="video"), sa.Column("storage_key", sa.String(500), nullable=False, unique=True), sa.Column("public_url", sa.String(800)), sa.Column("mime_type", sa.String(120), nullable=False, server_default="application/octet-stream"), sa.Column("size_bytes", sa.Integer(), nullable=False, server_default="0"), sa.Column("metadata_json", sa.JSON(), nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_video_assets_project_id", "video_assets", ["project_id"]); op.create_index("ix_video_assets_job_id", "video_assets", ["job_id"])

def downgrade():
    op.drop_table("video_assets"); op.drop_constraint("uq_video_job_owner_idempotency", "video_generation_jobs", type_="unique"); op.drop_table("video_generation_jobs"); op.drop_constraint("uq_video_scene_order", "video_scenes", type_="unique"); op.drop_table("video_scenes"); op.drop_table("video_sources"); op.drop_table("video_projects")
