import React, { useEffect } from "react";
import { Navigate, NavLink, Outlet, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import { api, Course, Role, User } from "./api";
import { useAuth } from "./store";

const demoAccounts = [
  { label: "学生演示", username: "demo_student" },
  { label: "教师演示", username: "demo_teacher" },
  { label: "管理员演示", username: "demo_admin" },
];

function AuthPage({ mode }: { mode: "login" | "register" }) {
  const navigate = useNavigate(); const { user, login } = useAuth();
  const [username, setUsername] = React.useState(""); const [email, setEmail] = React.useState(""); const [name, setName] = React.useState(""); const [password, setPassword] = React.useState(""); const [confirm, setConfirm] = React.useState(""); const [show, setShow] = React.useState(false); const [loading, setLoading] = React.useState(false);
  if (user) return <Navigate to="/" replace />;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (mode === "register" && password !== confirm) { toast.error("两次密码不一致"); return; } setLoading(true); try { if (mode === "login") { const next = await login(username, password); navigate(next.role === "student" ? "/student" : next.role === "teacher" ? "/teacher" : "/admin"); } else { const { data } = await api.post("/auth/register", { username, email, password, name }); useAuth.getState().setUser(data.user); navigate("/"); toast.success("注册成功"); } } catch (error: any) { toast.error(error.response?.data?.detail || "操作失败，请稍后重试"); } finally { setLoading(false); } };
  const fillDemo = (account: typeof demoAccounts[number]) => { setUsername(account.username); setPassword("123456"); };
  return <main className="auth-page"><div className="auth-glow" /><section className="auth-hero"><p className="eyebrow">HKU · INTELLIGENT EDU</p><h1>让每一堂课<br /><span>更有洞察力。</span></h1><p>为教师、学生与管理者打造统一、清晰、可持续的智能教学工作台。</p></section><section className="auth-card"><div className="brand-mark">IE</div><h2>{mode === "login" ? "欢迎回来" : "创建账户"}</h2><p className="muted">{mode === "login" ? "登录你的校园教学空间" : "注册后即可开始学习"}</p><form onSubmit={submit}>{mode === "register" && <><label>姓名<input value={name} onChange={e => setName(e.target.value)} placeholder="你的姓名" /></label><label>邮箱<input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="name@hku.hk" /></label></>}<label>用户名或邮箱<input required value={username} onChange={e => setUsername(e.target.value)} placeholder="输入用户名" autoComplete="username" /></label><label>密码<div className="password-wrap"><input required type={show ? "text" : "password"} value={password} onChange={e => setPassword(e.target.value)} placeholder="至少 6 位字符" autoComplete={mode === "login" ? "current-password" : "new-password"} /><button type="button" className="eye" onClick={() => setShow(!show)}>{show ? "隐藏" : "显示"}</button></div></label>{mode === "register" && <label>确认密码<input required type="password" value={confirm} onChange={e => setConfirm(e.target.value)} placeholder="再次输入密码" /></label>}<button className="primary-btn" disabled={loading}>{loading ? "处理中…" : mode === "login" ? "登录 →" : "创建账户 →"}</button></form>{mode === "login" && import.meta.env.DEV && <div className="demo-box"><strong>本地演示账户</strong><div className="demo-buttons">{demoAccounts.map(a => <button key={a.username} onClick={() => fillDemo(a)}>{a.label}</button>)}</div><small>密码统一为 123456</small></div>}<p className="switch">{mode === "login" ? "还没有账户？" : "已有账户？"}<button onClick={() => navigate(mode === "login" ? "/register" : "/login")}>{mode === "login" ? "注册" : "登录"}</button></p></section></main>;
}

function Header() { const { user, logout } = useAuth(); const navigate = useNavigate(); return <header className="topbar"><div className="logo" onClick={() => navigate("/")}>IE <span>Intelligent Edu</span></div><div className="top-actions"><span className="role-pill">{user?.role}</span><span className="avatar">{user?.name?.slice(0, 1).toUpperCase()}</span><span className="user-name">{user?.name}</span><button className="ghost-btn" onClick={() => logout().then(() => navigate("/login"))}>退出</button></div></header>; }
function Shell() { const { user } = useAuth(); const links: { to: string; label: string; roles: Role[] }[] = [{ to: "/", label: "总览", roles: ["teacher", "student", "admin"] }, { to: "/courses", label: "课程", roles: ["teacher", "student", "admin"] }, { to: "/assignments", label: "作业", roles: ["teacher", "student"] }, { to: "/admin", label: "管理后台", roles: ["admin"] }]; return <div className="app-shell"><Header /><aside>{links.filter(l => user && l.roles.includes(user.role)).map(l => <NavLink key={l.to} to={l.to} end={l.to === "/"}>{l.label}</NavLink>)}</aside><div className="content"><Outlet /></div></div>; }
function Protected() { const { user, loading } = useAuth(); const location = useLocation(); if (loading) return <div className="loading-screen">正在恢复登录状态…</div>; return user ? <Shell /> : <Navigate to={`/login?next=${encodeURIComponent(location.pathname)}`} replace />; }
function Dashboard() { const { user } = useAuth(); return <div><div className="page-heading"><div><p className="eyebrow">{user?.role?.toUpperCase()} WORKSPACE</p><h1>你好，{user?.name}</h1><p className="muted">这是你的教学空间概览。</p></div></div><div className="stats-grid"><div className="stat-card"><span>当前角色</span><strong>{user?.role}</strong><small>权限已隔离</small></div><div className="stat-card"><span>课程空间</span><strong>1</strong><small>Phase 1 演示数据</small></div><div className="stat-card"><span>待处理事项</span><strong>2</strong><small>来自课程与作业</small></div></div><div className="welcome-panel"><h2>统一教学骨架已就绪</h2><p>课程、作业、文件和 AI 对话将在同一套角色感知的工作台中逐步展开。</p></div></div>; }
function Courses() { const [courses, setCourses] = React.useState<Course[]>([]); const { user } = useAuth(); useEffect(() => { api.get<Course[]>("/courses").then(r => setCourses(r.data)).catch(() => undefined); }, []); return <div><div className="page-heading"><div><p className="eyebrow">ACADEMIC</p><h1>课程</h1><p className="muted">{user?.role === "student" ? "你已加入的课程" : "你负责或可管理的课程"}</p></div></div><div className="course-grid">{courses.map(c => <article className="course-card" key={c.id}><span className="course-code">{c.code}</span><h2>{c.name}</h2><p>{c.description}</p><footer><span>教师：{c.teacher_name}</span><span>{c.enrolled_count} 名学生</span></footer></article>)}{!courses.length && <div className="empty">暂无课程数据</div>}</div></div>; }
function Assignments() { return <div><div className="page-heading"><div><p className="eyebrow">COURSEWORK</p><h1>作业</h1><p className="muted">Phase 1 作业列表与提交入口。</p></div></div><div className="welcome-panel"><h2>作业工作台</h2><p>教师发布、学生提交、评分反馈的数据链路已在后端准备完成。</p></div></div>; }
function Admin() { return <div><div className="page-heading"><div><p className="eyebrow">ADMINISTRATION</p><h1>管理后台</h1><p className="muted">管理账户、课程和审计能力将在这里扩展。</p></div></div><div className="welcome-panel"><h2>管理员空间</h2><p>当前登录账户具备 admin 权限，后续可接入用户、课程与系统配置管理。</p></div></div>; }

export default function App() { const bootstrap = useAuth(s => s.bootstrap); useEffect(() => { bootstrap(); }, [bootstrap]); return <Routes><Route path="/login" element={<AuthPage mode="login" />} /><Route path="/register" element={<AuthPage mode="register" />} /><Route element={<Protected />}><Route path="/" element={<Dashboard />} /><Route path="/student" element={<Dashboard />} /><Route path="/teacher" element={<Dashboard />} /><Route path="/admin" element={<Admin />} /><Route path="/courses" element={<Courses />} /><Route path="/assignments" element={<Assignments />} /></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes>; }
