import React, { useEffect, useState } from "react";
import { fileAssetsApi, pptApi, type AvailablePptExport, type FileAsset, type PptProject } from "../../api";
import toast from "react-hot-toast";

export default function FileUploadModal({ open, onClose, onSubmit, title = "上传文件", accept = ".pdf,.ppt,.pptx,.doc,.docx,.xls,.xlsx,.txt,.md,.markdown,image/*", extra }: { open: boolean; onClose: () => void; onSubmit: (assets: FileAsset[]) => Promise<void>; title?: string; accept?: string; extra?: React.ReactNode }) {
  const [files, setFiles] = useState<File[]>([]); const [pptx, setPptx] = useState<AvailablePptExport[]>([]); const [projects, setProjects] = useState<Record<string, PptProject>>({}); const [selected, setSelected] = useState<string[]>([]); const [query, setQuery] = useState(""); const [busy, setBusy] = useState(false); const [drag, setDrag] = useState(false); const [previewUrls, setPreviewUrls] = useState<Record<string, string>>({});
  useEffect(() => { if (open) { setFiles([]); setSelected([]); setQuery(""); Promise.all([fileAssetsApi.availablePpt(), pptApi.projects()]).then(([a, p]) => { setPptx(a.data.items); setProjects(Object.fromEntries(p.data.items.map(x => [x.id, x]))); }).catch(() => { setPptx([]); setProjects({}); }); } }, [open]);
  useEffect(() => { let cancelled = false; pptx.slice(0, 12).forEach(async x => { const url = projects[x.project_id]?.cover_preview_url; if (!url || previewUrls[x.project_id]) return; try { const response = await pptApi.preview(url); if (!cancelled) setPreviewUrls(current => ({ ...current, [x.project_id]: URL.createObjectURL(response.data) })); } catch { /* preview remains a styled placeholder */ } }); return () => { cancelled = true; }; }, [pptx, projects]);
  if (!open) return null;
  const addFiles = (incoming: File[]) => setFiles(current => [...current, ...incoming.filter(f => !current.some(x => x.name === f.name && x.size === f.size))]);
  const submit = async () => { if (!files.length && !selected.length) return; setBusy(true); try { const assets: FileAsset[] = []; for (const file of files) assets.push((await fileAssetsApi.upload(file)).data); for (const id of selected) assets.push((await fileAssetsApi.copyPpt(id)).data); await onSubmit(assets); onClose(); } catch (e: any) { toast.error(e.response?.data?.detail || "文件上传失败"); } finally { setBusy(false); } };
  return <div className="file-upload-modal-backdrop file-upload-modal-enter" onMouseDown={e => e.target === e.currentTarget && !busy && onClose()}><div className="file-upload-modal"><button className="modal-close" onClick={onClose}>×</button><h2>{title}</h2>{extra}<div className="file-upload-columns"><section className={`file-drop-zone ${drag ? "dragging" : ""}`} onDragEnter={e => { e.preventDefault(); setDrag(true); }} onDragOver={e => e.preventDefault()} onDragLeave={() => setDrag(false)} onDrop={e => { e.preventDefault(); setDrag(false); addFiles(Array.from(e.dataTransfer.files)); }}><i className="fas fa-cloud-arrow-up"/><strong>拖动文件到这里</strong><span>或</span><label className="primary-action">选择电脑文件<input hidden type="file" multiple accept={accept} onChange={e => addFiles(Array.from(e.target.files || []))}/></label><div className="upload-file-list">{files.map((f,i)=><span key={i}>📎 {f.name}<button onClick={() => setFiles(x => x.filter((_,j) => j !== i))}>×</button></span>)}</div></section><section className="ppt-export-picker"><header><strong>PPT Agent 最近项目</strong><input placeholder="搜索课件" value={query} onChange={e => setQuery(e.target.value)}/></header><div className="ppt-upload-project-grid">{pptx.filter(x => x.title.toLowerCase().includes(query.toLowerCase()) || x.file_name.toLowerCase().includes(query.toLowerCase())).map(x => <label className={`ppt-upload-project-card ${selected.includes(x.export_id) ? "selected" : ""}`} key={x.export_id}><input type="checkbox" checked={selected.includes(x.export_id)} onChange={() => setSelected(s => s.includes(x.export_id) ? s.filter(id => id !== x.export_id) : [...s, x.export_id])}/><div className="ppt-upload-cover">{previewUrls[x.project_id] ? <img src={previewUrls[x.project_id]} alt=""/> : <><i className="fas fa-file-powerpoint"/><span>PPTX</span></>}</div><div className="ppt-upload-project-info"><b>{x.title}</b><small>{x.file_name}</small><span>{new Date(x.created_at).toLocaleDateString("zh-CN")} · {(x.size_bytes / 1024 / 1024).toFixed(1)} MB</span></div></label>)}</div>{!pptx.length && <div className="upload-empty">暂无已导出的 PPTX</div>}</section></div><footer><span>{files.length + selected.length} 个文件待上传</span><button className="primary-action" disabled={busy || (!files.length && !selected.length)} onClick={() => void submit()}>{busy ? "上传中…" : "开始上传"}</button></footer></div></div>;
}
